name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            cpp_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: g++

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies on Windows
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install glfw3:x64-windows

      # Install dependencies on Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libglfw3-dev \
            libglm-dev \
            mesa-utils \
            libglew-dev \
            libgl1-mesa-dev \
            freeglut3-dev

      # Configure CMake
      - name: Configure CMake
        run: |
          cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}/vcpkg/installed/x64-windows

      # Build the project
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      # Test the project
      - name: Test
        working-directory: build
        run: ctest --build-config ${{ matrix.build_type }}
